name: Create web page

on: [push] 

jobs: 
  build: 
   runs-on: ubuntu-latest 
   env: 
    working-directory: ./Source
   
   steps: 
   
   - uses: actions/checkout@v1 
   
   - name: Run make4ht 
     uses: docker://michalh21/make4ht-docker:latest 
     env: 
       command: "make4ht -u -d out main.tex" 
       
   - name: Publish the web pages 
     uses: peaceiris/actions-gh-pages@v2.5.0 
     env: 
       github_token: ${{ secrets.GITHUB_TOKEN }} 
       PUBLISH_DIR: ./out
